import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Search, SlidersHorizontal, Bookmark, ArrowUpRight, GraduationCap, MapPin, CalendarDays, Sparkles, Sun, Moon, ChevronDown, X, Compass, BookOpen, MessageCircle, Settings2, Check, Clock3, CircleDollarSign, Globe2, Heart, Bell, UserRound, ExternalLink, Send, WandSparkles, ShieldCheck, FileText, Target } from 'lucide-react';
import scholarships from '../data/scholarships.json';
import './styles.css';

const FLAG = { 'United States':'🇺🇸', China:'🇨🇳', Germany:'🇩🇪', Europe:'🇪🇺', 'United Kingdom':'🇬🇧', France:'🇫🇷', Netherlands:'🇳🇱', Switzerland:'🇨🇭', Australia:'🇦🇺', 'New Zealand':'🇳🇿' };
const stored = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } };
const fmtDate = (iso) => { if (!iso) return null; const d = new Date(iso + 'T00:00:00'); return Number.isNaN(d.getTime()) ? iso : d.toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' }); };
function App() {
 const [view,setView]=useState('discover'), [query,setQuery]=useState(''), [country,setCountry]=useState('All destinations'), [field,setField]=useState('All fields'), [level,setLevel]=useState('Any degree'), [sort,setSort]=useState('Best match'), [saved,setSaved]=useState(()=>stored('sh-saved',[])), [profile,setProfile]=useState(()=>stored('sh-profile',{field:'Civil Engineering',degree:'Master',nationality:'',gpa:'',countries:[]})), [dark,setDark]=useState(()=>stored('sh-dark',false)), [selected,setSelected]=useState(null), [chat,setChat]=useState(''), [messages,setMessages]=useState([]), [provider,setProvider]=useState('None — use offline guide'), [apiKey,setApiKey]=useState(''), [showKey,setShowKey]=useState(false), [notice,setNotice]=useState('');
 const countries=['All destinations',...new Set(scholarships.map(s=>s.country))];
 const filtered=useMemo(()=>scholarships.filter(s=>{
   const hay=`${s.name} ${s.provider} ${s.country} ${s.university} ${s.description}`.toLowerCase();
   return (!query||hay.includes(query.toLowerCase()))&&(country==='All destinations'||s.country===country)&&(field==='All fields'||s.program_field.includes(field))&&(level==='Any degree'||s.degree_level.includes(level));
 }).sort((a,b)=>{
   if(sort==='A–Z')return a.name.localeCompare(b.name);
   if(sort==='Country')return a.country.localeCompare(b.country)||a.name.localeCompare(b.name);
   return (Number(saved.includes(b.id))-Number(saved.includes(a.id)))||a.name.localeCompare(b.name);
 }),[query,country,field,level,sort,saved]);
 const updateSaved=(id)=>{const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(next);localStorage.setItem('sh-saved',JSON.stringify(next));setNotice(next.includes(id)?'Added to your saved scholarships':'Removed from saved scholarships');setTimeout(()=>setNotice(''),2400)};
 const saveProfile=()=>{localStorage.setItem('sh-profile',JSON.stringify(profile));setNotice('Your profile is saved on this device');setTimeout(()=>setNotice(''),2400)};
 const go=(next)=>{setView(next);setSelected(null)};
 const matching=(s)=>{let score=55;if(profile.field&&s.program_field.includes(profile.field))score+=20;if(profile.degree&&s.degree_level.includes(profile.degree))score+=15;if(profile.nationality&&s.eligibility.nationality.some(n=>n.toLowerCase().includes(profile.nationality.toLowerCase())||n.toLowerCase().includes('worldwide')))score+=10;return Math.min(96,score)};
 const answer=(text)=>{let q=text||chat;if(!q.trim())return;const eligible=scholarships.filter(s=>(!profile.field||s.program_field.includes(profile.field))&&(!profile.degree||s.degree_level.includes(profile.degree))).slice(0,3);const response=`Based on your saved profile (${profile.field || 'your field'} · ${profile.degree || 'degree level'}), start by reviewing ${eligible.map(s=>s.name).join(', ')}. These are discovery suggestions—not an eligibility decision. Nationality, current calls, and each official program's rules matter. Open the official links to verify details before applying.`;setMessages(m=>[...m,{from:'you',text:q},{from:'assistant',text:response}]);setChat('')};
 const nav=[['discover','Discover',Compass],['saved','My shortlist',Bookmark],['profile','My profile',UserRound],['assistant','AI assistant',Sparkles],['settings','AI settings',Settings2]];
 return <div className={dark?'app dark':'app'}>
  <aside className="sidebar"><div className="brand"><span className="brand-mark"><GraduationCap size={21}/></span><span>scholar<span className="brand-accent">hub</span></span></div><div className="workspace-label">YOUR WORKSPACE</div><nav>{nav.map(([key,label,Icon])=><button key={key} className={`nav-item ${view===key?'active':''}`} onClick={()=>go(key)} title={label} aria-current={view===key?'page':undefined}><Icon size={18}/>{label}{key==='saved'&&saved.length>0&&<span className="nav-count">{saved.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="help-card"><div className="help-icon"><BookOpen size={17}/></div><div><strong>New to scholarships?</strong><p>Our guide makes it simple.</p><button onClick={()=>setView('assistant')}>Explore the guide <ArrowUpRight size={13}/></button></div></div><button className="theme-toggle" onClick={()=>{const next=!dark;setDark(next);localStorage.setItem('sh-dark',JSON.stringify(next))}}>{dark?<Sun size={17}/>:<Moon size={17}/>}<span>{dark?'Light':'Dark'} appearance</span><span className="toggle-pill"><i/></span></button><div className="privacy"><ShieldCheck size={15}/> Your data stays on this device</div></div></aside>
  <main className="main"><header className="topbar"><div className="breadcrumbs">ScholarHub <span>/</span> <b>{nav.find(n=>n[0]===view)?.[1]||'Details'}</b></div><div className="top-actions"><span className="open-label"><i/> Open access · No account needed</span><button className="icon-btn" aria-label="Notifications" onClick={()=>go('saved')}><Bell size={18}/></button><div className="avatar">S</div></div></header>
  {view==='discover'&&<><section className="welcome"><div className="eyebrow"><Sparkles size={14}/> YOUR NEXT CHAPTER STARTS HERE</div><h1>Find funding for<br/><em>what moves you.</em></h1><p className="hero-copy">A calmer way to discover scholarships for engineering students around the world.</p><div className="hero-stats"><div><strong>{scholarships.length}</strong><span>curated opportunities</span></div><div className="stat-divider"/><div><strong>{countries.length-1}</strong><span>destinations to explore</span></div><div className="stat-divider"/><div><strong>Free</strong><span>always, no sign-up</span></div></div><div className="hero-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="art-sun"/><div className="art-cap"><GraduationCap size={80} strokeWidth={1}/></div><div className="art-leaf leaf-one"/><div className="art-leaf leaf-two"/><span className="sparkle s1">✳</span><span className="sparkle s2">✦</span></div></section>
  <section className="discovery"><div className="section-heading"><div><div className="eyebrow muted">THE OPPORTUNITY BOARD</div><h2>Scholarships worth a look</h2><p>Hand-picked places to start your search. Always confirm details with the provider.</p></div><button className="outline-btn" onClick={()=>go('profile')}><SlidersHorizontal size={15}/> Personalize results</button></div>
   <div className="filterbar"><label className="searchbox"><Search size={17}/><input aria-label="Search scholarships" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try a university, country, or keyword…"/><kbd>⌘ K</kbd></label><select value={country} onChange={e=>setCountry(e.target.value)} aria-label="Filter by destination">{countries.map(c=><option key={c}>{c}</option>)}</select><select value={field} onChange={e=>setField(e.target.value)} aria-label="Filter by field"><option>All fields</option><option>Civil Engineering</option><option>Materials Science</option></select><select value={level} onChange={e=>setLevel(e.target.value)} aria-label="Filter by degree"><option>Any degree</option>{['Bachelor','Master','PhD','PostDoc'].map(x=><option key={x}>{x}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort scholarships"><option>Best match</option><option>A–Z</option><option>Country</option></select></div>
   <div className="results-meta"><span><b>{filtered.length}</b> opportunities to explore</span><span><span className="live-dot"/> Details change — verify at the official source</span></div>
   <div className="scholarship-grid">{filtered.map((s,i)=><article className="scholarship-card" key={s.id}><div className="card-top"><div className={`card-icon icon-${i%5}`}>{s.country==='Europe'?<Globe2 size={20}/>:<span>{FLAG[s.country]||'🌐'}</span>}</div><button className={`save-btn ${saved.includes(s.id)?'saved':''}`} aria-label={saved.includes(s.id)?'Remove from saved':'Save scholarship'} onClick={()=>updateSaved(s.id)}><Bookmark size={17} fill={saved.includes(s.id)?'currentColor':'none'}/></button></div><div className="card-country">{s.country.toUpperCase()} <span>·</span> {s.provider}</div><h3>{s.name}</h3><div className="university"><GraduationCap size={14}/>{s.university}</div><p className="card-description">{s.description}</p><div className="chip-row">{s.degree_level.map(d=><span className="chip" key={d}>{d}</span>)}<span className="chip field-chip">{s.program_field[0]}</span>{s.deadline&&<span className="chip deadline-chip"><CalendarDays size={11}/>{fmtDate(s.deadline)}</span>}<span className={`status-badge status-${s.status}`}>{s.status==='verify'?'Verify cycle':s.status}</span></div><div className="card-footer"><div className="match"><span className="match-ring">{matching(s)}%</span><span>profile fit*</span></div><button className="details-link" onClick={()=>setSelected(s)}>View details <ArrowUpRight size={15}/></button></div></article>)}</div>
   {filtered.length===0&&<div className="empty-state"><Search size={30}/><h3>No matches just yet</h3><p>Try another keyword or clear a filter.</p><button className="outline-btn" onClick={()=>{setQuery('');setCountry('All destinations');setField('All fields');setLevel('Any degree')}}>Clear filters</button></div>}
   <p className="disclaimer">* Profile fit is a simple local heuristic, not an eligibility assessment. Dates and award values are shown only where a contributor recorded a verified source; confirm every detail with the official provider.</p>
  </section></>}
  {view==='saved'&&<section className="page-section"><div className="eyebrow muted">YOUR PERSONAL SHORTLIST</div><h1 className="page-title">Saved <em>for later.</em></h1><p className="page-lede">Keep the opportunities you’re considering in one quiet corner.</p>{scholarships.filter(s=>saved.includes(s.id)).length===0?<div className="empty-state"><Bookmark size={30}/><h3>Your shortlist is waiting</h3><p>Save a scholarship while exploring to see it here.</p><button className="primary-btn" onClick={()=>go('discover')}>Explore scholarships <ArrowUpRight size={15}/></button></div>:<div className="scholarship-grid">{scholarships.filter(s=>saved.includes(s.id)).map(s=><article className="scholarship-card compact" key={s.id}><div className="card-top"><div className="card-icon">{FLAG[s.country]||'🌐'}</div><button className="save-btn saved" onClick={()=>updateSaved(s.id)} aria-label="Remove saved"><Bookmark size={17} fill="currentColor"/></button></div><div className="card-country">{s.country.toUpperCase()}</div><h3>{s.name}</h3><p className="card-description">{s.description}</p><button className="details-link" onClick={()=>setSelected(s)}>View details <ArrowUpRight size={15}/></button></article>)}</div>}</section>}
  {view==='profile'&&<section className="page-section"><div className="eyebrow muted">A LITTLE ABOUT YOU</div><h1 className="page-title">Make it <em>personal.</em></h1><p className="page-lede">A few details help us bring relevant opportunities closer. Everything stays in this browser.</p><div className="form-card"><div className="form-heading"><div className="form-icon"><UserRound size={19}/></div><div><h3>Your study goals</h3><p>Update anytime. Nothing is sent to a server.</p></div></div><div className="form-grid"><label>Field of interest<select value={profile.field||'Civil Engineering'} onChange={e=>setProfile({...profile,field:e.target.value})}><option>Civil Engineering</option><option>Materials Science</option></select></label><label>Degree you're aiming for<select value={profile.degree||'Master'} onChange={e=>setProfile({...profile,degree:e.target.value})}><option>Bachelor</option><option>Master</option><option>PhD</option><option>PostDoc</option></select></label><label>Nationality / country of origin<input value={profile.nationality||''} onChange={e=>setProfile({...profile,nationality:e.target.value})} placeholder="e.g. India"/></label><label>Current GPA (optional)<input value={profile.gpa||''} onChange={e=>setProfile({...profile,gpa:e.target.value})} placeholder="e.g. 3.7 / 4.0"/></label><label>Preferred destination<input value={profile.preferred||''} onChange={e=>setProfile({...profile,preferred:e.target.value})} placeholder="e.g. Germany, Australia"/></label><label>Language test scores<input value={profile.language||''} onChange={e=>setProfile({...profile,language:e.target.value})} placeholder="IELTS, TOEFL, etc."/></label></div><div className="privacy-note"><ShieldCheck size={17}/><span><strong>Private by design.</strong> Your profile is saved in local storage on this device. Clearing browser data removes it.</span></div><button className="primary-btn" onClick={saveProfile}><Check size={16}/> Save my profile</button></div></section>}
  {view==='assistant'&&<section className="page-section assistant-page"><div className="eyebrow muted"><Sparkles size={13}/> YOUR THOUGHTFUL SCHOLARSHIP COMPANION</div><h1 className="page-title">A little help, <em>on your terms.</em></h1><p className="page-lede">Get started with a local guide—or connect an AI model you trust in settings.</p><div className="chat-card"><div className="chat-top"><div className="assistant-orb"><Sparkles size={19}/></div><div><b>Scholarship guide</b><span><i/> Offline · No model connected</span></div><button className="icon-btn" onClick={()=>go('settings')}><Settings2 size={18}/></button></div><div className="chat-body">{messages.length===0?<div className="chat-welcome"><div className="welcome-spark">✦</div><h3>Where would you like to begin?</h3><p>I can help you think through your search. For current eligibility and calls, official program pages are always the source of truth.</p><div className="suggestions">{['What should I check before applying?','Help me plan a scholarship search','Which opportunities fit my study goals?'].map(x=><button key={x} onClick={()=>answer(x)}>{x}<ArrowUpRight size={14}/></button>)}</div></div>:messages.map((m,i)=><div className={`chat-message ${m.from}`} key={i}><div className="message-avatar">{m.from==='you'?'S':<Sparkles size={14}/>}</div><div>{m.text}</div></div>)}</div><form className="chat-input" onSubmit={e=>{e.preventDefault();answer()}}><input value={chat} onChange={e=>setChat(e.target.value)} placeholder="Ask a question or explore an idea…" aria-label="Ask the scholarship assistant"/><button aria-label="Send question"><Send size={17}/></button></form><p className="chat-disclaimer">AI suggestions are informational, can be incomplete, and aren't a substitute for official scholarship requirements.</p></div></section>}
  {view==='settings'&&<section className="page-section"><div className="eyebrow muted">OPTIONAL · YOUR MODEL, YOUR CHOICE</div><h1 className="page-title">AI, <em>your way.</em></h1><p className="page-lede">ScholarHub works without AI. If you connect a provider, its policies determine how your prompts are handled.</p><div className="settings-card"><div className="settings-row"><div className="settings-icon"><WandSparkles size={19}/></div><div><h3>Choose a provider</h3><p>Provider calls are made directly from your browser; never enter a key on a shared device.</p></div></div><label className="setting-label">AI provider<select value={provider} onChange={e=>setProvider(e.target.value)}><option>None — use offline guide</option><option>OpenAI-compatible API</option><option>Ollama (local)</option><option>LM Studio (local)</option><option>Google Gemini (coming soon)</option><option>Anthropic Claude (coming soon)</option><option>Groq (coming soon)</option><option>OpenRouter (coming soon)</option></select></label>{provider!=='None — use offline guide'&&<><label className="setting-label">API key (optional for local models)<div className="secret-input"><input type={showKey?'text':'password'} value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="Paste your key for this session" autoComplete="off"/><button type="button" onClick={()=>setShowKey(!showKey)}>{showKey?'Hide':'Show'}</button></div></label><div className="privacy-note"><ShieldCheck size={17}/><span>Key stays in memory for this tab only and is not persisted or sent to ScholarHub servers. Provider requests leave your browser when you use the assistant.</span></div></>}<div className="provider-info"><div><span className="status-indicator"/>No connection configured</div><button className="outline-btn" onClick={()=>setNotice('Provider adapters are not connected yet — offline guide remains available')}>Test connection</button></div><div className="coming-note"><Clock3 size={16}/><span><b>Coming next:</b> provider-specific adapters, connection checks, and transparent per-model cost estimates. No API key is currently transmitted.</span></div></div></section>}
  {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="detail-modal" role="dialog" aria-modal="true" aria-label={selected.name} onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)} aria-label="Close details"><X size={20}/></button><div className="eyebrow muted">{FLAG[selected.country]||'🌐'} &nbsp;{selected.country.toUpperCase()}</div><h2>{selected.name}</h2><p className="detail-provider">{selected.provider} · {selected.university}</p><p className="detail-desc">{selected.description}</p><div className="detail-grid"><div><span>Degree levels</span><b>{selected.degree_level.join(', ')}</b></div><div><span>Funding</span><b>{selected.funding_type}</b></div><div><span>Deadline</span><b>{selected.deadline?fmtDate(selected.deadline):'Not maintained — check official source'}</b>{selected.deadline_notes&&<em className="deadline-note">{selected.deadline_notes}</em>}</div><div><span>Amount</span><b>{selected.amount}</b></div><div><span>Location</span><b>{selected.city}, {selected.region}</b></div><div><span>Eligibility</span><b>{selected.eligibility.nationality.join('; ')}</b></div><div><span>Source last checked</span><b>{selected.last_verified?fmtDate(selected.last_verified):'Not recorded'}</b></div></div><div className="detail-note"><ShieldCheck size={17}/><span>Deadlines and amounts appear only where a contributor recorded them from the official source, together with the date they checked it. Confirm dates, eligibility, and terms directly with the provider.</span></div><div className="modal-actions"><button className="outline-btn" onClick={()=>updateSaved(selected.id)}><Bookmark size={15}/>{saved.includes(selected.id)?'Saved':'Save opportunity'}</button><a className="primary-btn" href={selected.official_url} target="_blank" rel="noreferrer">Official scholarship page <ExternalLink size={15}/></a></div></section></div>}
  {notice&&<div className="toast"><Check size={16}/>{notice}</div>}<footer className="footer">Made for curious minds. <span>ScholarHub is an independent discovery tool · Always verify with official sources.</span></footer></main></div>
}

createRoot(document.getElementById('root')).render(<App/>);
